'use strict';
const $=id=>document.getElementById(id),D=JSON.parse($('anatomy').textContent);
const palette=['#71e0cf','#f5bb73','#a899fa','#f28faf','#74bdf9','#d5e779','#fd9c83','#65dcb5','#c8a3df','#faf4bf','#81d3e5','#eaaedf'];
const defs=[['radius','Cable radius (µm)',.25,.05,2,.05,'Larger: more area and stronger internal coupling.'],['resistivity','Axial resistivity (Ω·cm)',150,1,2000,10,'Larger: weaker internal conduction.'],['cm','Specific capacitance (µF/cm²)',1,.1,5,.1,'Larger: more capacitance and leak at fixed tau.'],['tau','Leak time constant (ms)',20,1,200,1,'Larger: weaker leak and longer persistence.'],['cellC','Bridge / balancer C (pF)',.5,.01,10,.1,'Larger: smaller response to fixed input.'],['gain','Current scale / contact (pA)',.05,0,1,.01,'Saturating strength; zero disables synapses.'],['scale','Synaptic voltage scale (mV)',5,.1,50,.5,'Larger: weaker sensitivity near rest.'],['sign','All-contact sign',1,-1,1,2,'A uniform hypothesis, not measured transmitter identity.'],['axial','Internal conductance ×',1,0,10,.1,'Larger: stronger coupling without extra membrane.']];
$('parameters').innerHTML=defs.map(([k,l,v,min,max,step,h])=>`<label>${l}${k==='sign'?'<select id="p-sign"><option value="1">+1 · positive coupling</option><option value="-1">−1 · negative coupling</option></select>':`<input id="p-${k}" type="number" min="${min}" max="${max}" step="${step}" value="${v}">`}<small>${h}</small></label>`).join('');
const ann=D.cells.map((c,i)=>[c,i]).filter(([c])=>c.type==='ANN');
for(const [c,i] of ann)$('show').add(new Option(c.name,i));
D.cells.forEach((c,i)=>$('cellChoice').add(new Option(c.name+' · '+c.id,i)));
const central=D.owner[D.stimulus];$('cellChoice').value=central;
let stimulus=D.stimulus,cutEdge=D.defaultCut,params=Object.fromEntries(defs.map(([k,l,v])=>[k,v]));Object.assign(params,{dt:.5,feedback:true,cut:-1});
let probes=[{kind:'cell',index:central,label:'ANN Q1–4 · mean'},{kind:'node',index:stimulus,label:'Input location · node '+D.nodeIds[stimulus]},{kind:'group',type:'balancer',label:'Balancer cells · mean'}];
let samples=[],events=[],time=0,v=new Float64Array(D.baseC.length),pv=new Float64Array(D.cells.length),running=false,busy=false,ready=false,nextId=0,pending=new Map(),epoch=0;
let initialParams={...params},achieved=0,rateTime=0,rateWall=performance.now();
const workerURL=URL.createObjectURL(new Blob([$ ('kernel').textContent+'\n'+$('worker').textContent],{type:'text/javascript'}));let worker;
function event(kind,data={}){events.push({time_ms:time,kind,...data});$('events').textContent=events.slice(-7).map(e=>`${e.time_ms.toFixed(1)} ms · ${e.kind}${e.description?' · '+e.description:''}`).join('\n');$('events').style.whiteSpace='pre-line';}
function report(s,error=false){$('status').textContent=s;$('status').style.color=error?'#ffaca5':'#6be0ce';}
function ask(type,extra={}){return new Promise((resolve,reject)=>{const id=++nextId;pending.set(id,{resolve,reject});worker.postMessage({id,type,...extra});});}
function launch(){if(worker)worker.terminate();for(const x of pending.values())x.reject(Error('Reset'));pending.clear();worker=new Worker(workerURL);worker.onmessage=({data:m})=>{if(m.error){const r=pending.get(m.id);pending.delete(m.id);if(r)r.reject(Error(m.error));return;}time=m.time;v=m.v;pv=m.pv;params=m.params;if(m.rows?.length){samples.push(...m.rows);if(samples.length>10000)samples.splice(0,samples.length-10000);}const r=pending.get(m.id);pending.delete(m.id);if(r)r.resolve(m);};worker.onerror=e=>{setRun(false);ready=false;report('Worker failed: '+e.message,true);for(const x of pending.values())x.reject(Error(e.message));pending.clear();};}
function readControls(){const p={dt:.5,feedback:$('feedback').checked,cut:$('cut').checked?cutEdge:-1};for(const [k,l,value,min,max] of defs){const x=+$('p-'+k).value;if(!Number.isFinite(x)||x<min||x>max||(k==='sign'&&![-1,1].includes(x)))throw Error('Check '+l);p[k]=x;}return p;}
function pulseControls(){const amplitude=+$('pulse').value,duration=+$('pulseLength').value;if(!Number.isFinite(amplitude)||Math.abs(amplitude)>20||!Number.isFinite(duration)||duration<.5||duration>1000)throw Error('Pulse must be ±20 pA or less and 0.5–1000 ms');return {amplitude,duration};}
function setRun(on){running=on;$('run').textContent=on?'Pause':'Run';lastTick=performance.now();}
async function reset(){let p,pulse;try{p=readControls();pulse=pulseControls();}catch(e){report(e.message,true);return;}setRun(false);epoch++;ready=false;busy=true;launch();time=0;samples=[];events=[];initialParams={...p};try{await ask('init',{data:D,params:p,probes,stimulus,demo:$('demo').checked,...pulse});event('reset',{parameters:p,probes:structuredClone(probes),stimulus,demo:$('demo').checked,pulse});ready=true;report('Ready · computed live');}catch(e){report(e.message,true);}finally{busy=false;for(const id of ['run','step','reset','inject'])$(id).disabled=!ready;draw();}}
async function transact(fn){if(!ready)return;try{await fn();draw();}catch(e){report(e.message,true);}}
async function setProbes(next){probes=next;await ask('probes',{probes});samples=[];event('probe set changed',{probes:structuredClone(probes),description:'new trace window; electrical state retained'});renderProbes();}
function addProbe(p){transact(async()=>{if(probes.some(x=>x.kind===p.kind&&x.index===p.index&&x.type===p.type))return report('That probe is already selected');if(probes.length>=12)return report('Remove a probe to add another (12 visible channels)');await setProbes([...probes,p]);report('Probe added · future samples recorded');});}
function probeValue(p,point=false){if(p.kind==='node')return point?pv[D.owner[p.index]]:v[p.index];const ids=p.kind==='cell'?D.cells[p.index].indices:D.cells.filter(c=>c.type===p.type).flatMap(c=>c.indices);let sum=0,weight=0;for(const i of ids){const c=D.xyz[i]?D.baseC[i]*params.radius/.25*params.cm:params.cellC;sum+=c*(point?pv[D.owner[i]]:v[i]);weight+=c;}return sum/weight;}
function renderProbes(){const body=$('probes');body.textContent='';probes.forEach((p,k)=>{const tr=document.createElement('tr');const name=document.createElement('td');name.className='probeName';const dot=document.createElement('span');dot.className='swatch';dot.style.background=palette[k];name.append(dot,document.createTextNode(p.label));tr.append(name);for(const point of [false,true]){const td=document.createElement('td');td.textContent=probeValue(p,point).toFixed(5);tr.append(td);}const td=document.createElement('td'),b=document.createElement('button');b.textContent='×';b.className='small';b.setAttribute('aria-label','Remove '+p.label);b.onclick=()=>transact(()=>setProbes(probes.filter((_,i)=>i!==k)));td.append(b);tr.append(td);body.append(tr);});}
let az=.1,el=-.12,zoom=1,drag=null,projected=[],extent=0;
const finite=D.xyz.filter(Boolean),center=[0,0,0];finite.forEach(p=>p.forEach((x,k)=>center[k]+=x/finite.length));const xyz=D.xyz.map(p=>p?p.map((x,k)=>x-center[k]):null);xyz.forEach(p=>{if(p)extent=Math.max(extent,Math.hypot(...p));});
function canvas(id){const c=$(id),r=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1;if(c.width!==Math.round(r.width*dpr)||c.height!==Math.round(r.height*dpr)){c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);return [ctx,r.width,r.height];}
function colorFor(x,range){const a=[85,119,139],b=x<0?[103,151,255]:[255,205,115],t=Math.min(1,Math.abs(x)/range);return `rgb(${a.map((c,k)=>Math.round(c+(b[k]-c)*t)).join(',')})`;}
function shown(i){return $('show').value==='all'||D.owner[i]===+$('show').value;}
function drawMorph(){const [ctx,w,h]=canvas('morph'),s=Math.min(w,h)*.46/extent*zoom,ca=Math.cos(az),sa=Math.sin(az),ce=Math.cos(el),se=Math.sin(el);projected=xyz.map(p=>{if(!p)return null;const x=p[0]*ca+p[2]*sa,z=-p[0]*sa+p[2]*ca,y=p[1]*ce-z*se;return [w/2+x*s,h/2+y*s];});const range=Math.max(.001,+$('range').value||1.5),identity=$('color').value==='cell';ctx.lineWidth=.8;D.edges.forEach(([a,b],k)=>{if(!shown(a)||k===params.cut)return;ctx.strokeStyle=identity?['#72ddca','#ea98b8','#edc078'][ann.findIndex(([,i])=>i===D.owner[a])]:colorFor((v[a]+v[b])/2,range);ctx.beginPath();ctx.moveTo(...projected[a]);ctx.lineTo(...projected[b]);ctx.stroke();});function ring(i,color,r){if(!projected[i]||!shown(i))return;ctx.strokeStyle=color;ctx.lineWidth=1.8;ctx.beginPath();ctx.arc(...projected[i],r,0,Math.PI*2);ctx.stroke();}probes.forEach((p,k)=>{if(p.kind==='node')ring(p.index,palette[k],4);});ring(stimulus,'white',8);if(params.cut>=0){const [a,b]=D.edges[params.cut];if(shown(a)){const x=(projected[a][0]+projected[b][0])/2,y=(projected[a][1]+projected[b][1])/2;ctx.strokeStyle='#ffc870';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-6,y-6);ctx.lineTo(x+6,y+6);ctx.moveTo(x-6,y+6);ctx.lineTo(x+6,y-6);ctx.stroke();}}$('neg').textContent='−'+range+' mV';$('pos').textContent='+'+range+' mV';$('sceneLabel').textContent=(identity?'Cell identity':'Spatial voltage')+' · '+time.toFixed(1)+' ms';}
function pick(x,y){let best=null,dist=144;D.edges.forEach(([a,b],edge)=>{if(!shown(a))return;const A=projected[a],B=projected[b],dx=B[0]-A[0],dy=B[1]-A[1],t=Math.max(0,Math.min(1,((x-A[0])*dx+(y-A[1])*dy)/(dx*dx+dy*dy||1)));const d=(x-A[0]-t*dx)**2+(y-A[1]-t*dy)**2;if(d<dist){dist=d;best={edge,index:t<.5?a:b};}});return best;}
function selectAt(x,y){const hit=pick(x,y);if(!hit)return report('Click closer to a visible branch; rotate or zoom to separate overlaps');const {index,edge}=hit,label=D.cells[D.owner[index]].name+' · node '+D.nodeIds[index];$('selection').textContent=label;$('nodeId').value=D.nodeIds[index];if($('action').value==='probe')addProbe({kind:'node',index,label});if($('action').value==='stimulus'){stimulus=index;event('input moved',{index,node:D.nodeIds[index]});report('Injection site moved · press Inject now');draw();}if($('action').value==='cut'){cutEdge=edge;$('cut').checked=true;transact(async()=>{await ask('params',{params:{cut:edge}});event('cable cut',{edge,description:'previous cut, if any, restored'});report('Cable disconnected');});}}
function drawChart(){const [ctx,w,h]=canvas('chart'),pad={l:58,r:12,t:22,b:35},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,windowMs=+$('window').value,end=Math.max(windowMs,time),start=Math.max(0,end-windowMs);const rows=samples.filter(r=>r[0]>=start);let lo=0,hi=0;for(const r of rows)for(let k=0;k<probes.length;k++){lo=Math.min(lo,r[1+k*2]);hi=Math.max(hi,r[1+k*2]);if($('compare').checked){lo=Math.min(lo,r[2+k*2]);hi=Math.max(hi,r[2+k*2]);}}if(hi-lo<1e-8)hi=.1;const margin=(hi-lo)*.12;hi+=margin;lo-=margin;const xx=t=>pad.l+(t-start)/windowMs*cw,yy=x=>pad.t+(hi-x)/(hi-lo)*ch;ctx.font='11px system-ui';ctx.fillStyle='#9db5c4';ctx.fillText('mV',8,12);for(let k=0;k<5;k++){const a=lo+(hi-lo)*k/4,y=yy(a);ctx.strokeStyle='#29414f';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(a.toFixed(Math.max(Math.abs(hi),Math.abs(lo))<.1?3:2),4,y+3);const t=start+windowMs*k/4;ctx.fillText(t.toFixed(0),xx(t)-10,h-14);}ctx.fillText('ms',w-24,h-1);ctx.save();ctx.beginPath();ctx.rect(pad.l,pad.t,cw,ch);ctx.clip();for(let k=0;k<probes.length;k++)for(const point of [false,true]){if(point&&!$('compare').checked)continue;ctx.strokeStyle=palette[k];ctx.lineWidth=point?1.2:2;ctx.setLineDash(point?[4,4]:[]);ctx.beginPath();const stride=Math.max(1,Math.floor(rows.length/cw));for(let j=0;j<rows.length;j+=stride){const r=rows[j],x=xx(r[0]),y=yy(r[1+2*k+(point?1:0)]);j?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}ctx.restore();ctx.setLineDash([]);}
function draw(){drawMorph();drawChart();renderProbes();$('clock').textContent=time.toFixed(1)+' ms';$('historyNote').textContent=`${samples.length.toLocaleString()} / 10,000 recent samples · probes start recording when added · export before reset`;}
$('run').onclick=()=>{if(ready)setRun(!running);};$('step').onclick=()=>transact(async()=>{setRun(false);await ask('advance',{steps:20});});$('reset').onclick=reset;
$('inject').onclick=()=>transact(async()=>{const pulse=pulseControls();const r=await ask('pulse',{index:stimulus,...pulse});event('current pulse',{...r.pulse,description:`${pulse.amplitude} pA into ${D.cells[D.owner[stimulus]].name}`});report('Pulse queued at '+r.pulse.start.toFixed(1)+' ms');});
$('apply').onclick=()=>transact(async()=>{const p=readControls();await ask('params',{params:p});event('parameters changed',{parameters:p,description:'voltage retained'});report('New parameters active');});
$('defaults').onclick=()=>{defs.forEach(([k,l,v])=>$('p-'+k).value=v);$('feedback').checked=true;$('cut').checked=false;cutEdge=D.defaultCut;$('pulse').value=1;$('pulseLength').value=20;stimulus=D.stimulus;reset();};
$('defaultCut').onclick=()=>{cutEdge=D.defaultCut;$('cut').checked=true;report('Balanced cut selected · press Apply');};
$('addCell').onclick=()=>{const i=+$('cellChoice').value;addProbe({kind:'cell',index:i,label:D.cells[i].name+' · mean'});};
$('addGroup').onclick=()=>{const type=$('group').value;addProbe({kind:'group',type,label:type+' cells · mean'});};
$('addNode').onclick=()=>{const id=$('nodeId').value.trim(),index=D.aliases[id];if(index===undefined)return report('Unknown ANN treenode ID; click the arbor to choose one',true);addProbe({kind:'node',index,label:D.cells[D.owner[index]].name+' · node '+id});};
$('inputCell').onclick=()=>{const i=+$('cellChoice').value;stimulus=D.cells[i].indices[0];$('selection').textContent='Input: '+D.cells[i].name+(D.cells[i].type==='ANN'?' · first exported compartment (use branch click to choose another)':' · single compartment');event('input moved',{index:stimulus});draw();};
$('clear').onclick=()=>{samples=[];event('trace window cleared');draw();};
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('csv').onclick=()=>{const quote=x=>'"'+String(x).replaceAll('"','""')+'"';download('combcircuit-live-traces.csv',[['time_ms',...probes.flatMap(p=>[p.label+' spatial_mV',p.label+' point_mV'])].map(quote).join(','),...samples.map(r=>r.join(','))].join('\n'),'text/csv');};
$('session').onclick=()=>download('combcircuit-live-experiment.json',JSON.stringify({version:'0.2',anatomy_source:D.source,source_manifest:'data/provenance.json',initial_parameters:initialParams,current_parameters:params,time_ms:time,events,probes,columns:['time_ms',...probes.flatMap(p=>[p.label+' spatial_mV',p.label+' point_mV'])],retained_samples:samples,note:'Log and retained traces, not a full-state checkpoint. Pair with bundled source data and code.'},null,2),'application/json');
$('viewReset').onclick=()=>{az=.1;el=-.12;zoom=1;drawMorph();};for(const id of ['show','color','range','compare','window'])$(id).onchange=draw;
$('morph').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};$('morph').setPointerCapture(e.pointerId);};$('morph').onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4)drag.moved=true;if(drag.moved){az+=dx*.008;el+=dy*.008;drawMorph();}drag.x=e.clientX;drag.y=e.clientY;};$('morph').onpointerup=e=>{if(drag&&!drag.moved){const r=$('morph').getBoundingClientRect();selectAt(e.clientX-r.left,e.clientY-r.top);}drag=null;};$('morph').onpointercancel=()=>drag=null;$('morph').addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.5,Math.min(6,zoom*Math.exp(-e.deltaY*.001)));drawMorph();},{passive:false});
let lastTick=performance.now(),lastDraw=0,budget=0;async function tick(now){const elapsed=Math.min(100,now-lastTick);lastTick=now;if(running&&ready&&!busy){budget=Math.min(128,budget+elapsed/1000*+$('speed').value);const steps=Math.min(256,Math.floor(budget/.5));if(steps){budget-=steps*.5;busy=true;const generation=epoch;try{await ask('advance',{steps});}catch(e){if(generation===epoch){setRun(false);report(e.message,true);}}finally{if(generation===epoch)busy=false;}}}if(now-lastDraw>70){draw();lastDraw=now;}if(now-rateWall>1000){achieved=(time-rateTime)/(now-rateWall)*1000;if(running)report('Live · '+Math.max(0,achieved).toFixed(0)+' ms / second achieved');rateTime=time;rateWall=now;}requestAnimationFrame(tick);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){setRun(false);report('Paused while tab is hidden');}});window.addEventListener('resize',draw);reset();requestAnimationFrame(tick);
